solutions = [
  {
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "managed": False,
    "name": "src",
    "custom_deps": {
        "src/android_webview/tools/cts_archive": None,
        "src/chrome/browser/resources/media_router/extension/src": None,
        "src/media/cdm/api": None,
        "src/third_party/accessibility_test_framework": None,
        "src/third_party/android_build_tools/aapt2": None,
        "src/third_party/android_build_tools/art": None,
        "src/third_party/android_build_tools/bundletool": None,
        "src/third_party/android_support_test_runner": None,
        "src/third_party/apache-portable-runtime/src": None,
        "src/third_party/apk-patch-size-estimator": None,
        "src/third_party/arcore-android-sdk/src": None,
        "src/third_party/bouncycastle": None,
        "src/third_party/byte_buddy": None,
        "src/third_party/depot_tools": None,
        "src/third_party/errorprone/lib": None,
        "src/third_party/espresso": None,
        "src/third_party/feed/src": None,
        "src/third_party/google-truth": None,
        "src/third_party/gson": None,
        "src/third_party/gvr-android-sdk/src": None,
        "src/third_party/hamcrest": None,
        "src/third_party/intellij": None,
        "src/third_party/swiftshader": None,
        "src/tools/gyp": None,
        "src/tools/luci-go": None,
        "src/tools/page_cycler/acid3": None,
        "src/third_party/icu4j": None,
        "src/third_party/mockito/src": None,
        "src/third_party/netty-tcnative/src": None,
        "src/third_party/netty4/src": None,
        "src/third_party/objenesis": None,
        "src/third_party/proguard": None,
        "src/third_party/protoc_javalite": None,
        "src/third_party/requests/src": None,
        "src/third_party/robolectric": None,
        "src/third_party/robolectric/robolectric": None,
        "src/third_party/androidx": None,
        "src/third_party/sqlite4java": None,
        "src/third_party/ub-uiautomator/lib": None,
        "src/third_party/xstream": None,
        "src/buildtools/clang_format/script": None,
        "src/chrome/test/data/perf/canvas_bench": None,
        "src/chrome/test/data/perf/frame_rate/content": None,
        "src/chrome/test/data/xr/webvr_info": None,
        "src/chrome/test/data/xr/webxr_samples": None,
        "src/third_party/spirv-cross/spirv-cross": None,
        "src/third_party/spirv-headers/src": None,
        "src/third_party/SPIRV-Tools/src": None,
        "src/third_party/shaderc/src": None,
        "src/third_party/dav1d/libdav1d": None,
        "src/third_party/glfw/src": None,
        "src/third_party/devtools-node-modules": None,
        "src/third_party/hunspell_dictionaries": None,
        "src/third_party/libFuzzer/src": None,
        "src/third_party/libaom/source/libaom": None,
        "src/third_party/libprotobuf-mutator/src": None,
        "src/third_party/openh264/src": None,
        "src/third_party/openscreen/src": None,
        "src/third_party/pyftpdlib/src": None,
        "src/third_party/quic_trace/src": None,
        "src/third_party/pywebsocket/src": None,
        "src/third_party/visualmetrics/src": None,
        "src/third_party/webdriver/pylib": None,
        "src/third_party/webgl/src": None,
        "src/third_party/webrtc": None,
        "src/tools/page_cycler/acid3": None,
        "src/tools/swarming_client": None,
        "src/third_party/android_ndk": None,
        "src/third_party/elfutils/src": None,
        "src/third_party/android_tools": None,
        "src/third_party/android_sdk/public": None,
    },
    "custom_vars": {
        "checkout_nacl": False,
        "checkout_configuration": "small",
    },
  },
]
target_os = ["android"]
target_os_only = "true"

